# Generated by Django 5.1.6 on 2025-02-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_start_date', models.DateField()),
            ],
            options={
                'db_table': 'department',
            },
        ),
    ]
