# Generated by Django 5.1.6 on 2025-02-28 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(max_length=20, unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('mobile_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('birth_date', models.DateField()),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('joining_date', models.DateField()),
                ('designations', models.CharField(max_length=255)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('qualification', models.CharField(max_length=255)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='teacher_images/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.department')),
            ],
        ),
    ]
