# Generated by Django 5.0.6 on 2025-03-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
