name: unicon
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0  # Added intl dependency
  mobile_scanner: ^6.0.6
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/article.jpg
    - assets/images/attendance.jpg
    - assets/images/timetable.jpg
    - assets/images/events.jpg
    - assets/images/GLS.png
    - assets/images/library.png
    - assets/images/mentor.jpg
    - assets/images/placement.png
    - assets/images/profile.png

  fonts:

    - family: SansSerifCollection
      fonts:
        - asset: assets/fonts/SansSerifCollection.ttf

    - family: Arial
      fonts:
        - asset: assets/fonts/arial.ttf

    - family: ArialBlack
      fonts:
        - asset: assets/fonts/arialblk.ttf
